runtime: php55

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: lMVTgOUknjMGoXGpWpV5j/qIOHDVLhpaMmuGwsA5x1w=
  STORAGE_DIR: /tmp